### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by energizer92** [eldar/pose-tensorflow#109]
Hi there,

i just installed everything as described and tryed to run the singleperson demo.
The following error was thrown:

` 2019-11-24 15:55:41.299791: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "demo/singleperson.py", line 9, in <module>
    from nnet import predict
  File "demo/..\nnet\predict.py", line 5, in <module>
    from nnet.net_factory import pose_net
  File "demo/..\nnet\net_factory.py", line 1, in <module>
    from nnet.pose_net import PoseNet
  File "demo/..\nnet\pose_net.py", line 4, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib' `

Did anyone had this same issue and might solved it ?

Thanks in advance

**Comment by energizer92** [comment]
I Solved this by downgrading tensorflow to version 1.14
