### ISSUE TITLE
dataset-test.mat is missing

### ISSUE THREAD

**Issue by PollenJain** [eldar/pose-tensorflow#11]
Where is **dataset-test.mat** is present which _load_dataset_ method of _PoseDataset class_ of _pose_dataset.py_ is calling?

**cfg.dataset** is equal to **dataset-test.mat**

Traceback (most recent call last):
  File "test.py", line 75, in <module>
    test_net(not args.novis, args.cache)
  File "test.py", line 20, in test_net
    dataset = create_dataset(cfg)
  File "/home/paragjain/Desktop/pose-tensorflow/dataset/factory.py", line 22, in create
    data = PoseDataset(cfg)
  File "/home/paragjain/Desktop/pose-tensorflow/dataset/pose_dataset.py", line 53, in __init__
    self.data = self.load_dataset()
  File "/home/paragjain/Desktop/pose-tensorflow/dataset/pose_dataset.py", line 67, in load_dataset
    mlab = sio.loadmat(file_name)
  File "/home/paragjain/anaconda3/envs/tensorflow2/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 135, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/paragjain/anaconda3/envs/tensorflow2/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 58, in mat_reader_factory
    byte_stream = _open_file(file_name, appendmat)
  File "/home/paragjain/anaconda3/envs/tensorflow2/lib/python2.7/site-packages/scipy/io/matlab/mio.py", line 23, in _open_file
    return open(file_like, 'rb')
IOError: [Errno 2] No such file or directory: 'dataset-test.mat'

**Comment by YYfangzi** [comment]
Have the same problem

**Comment by eldar** [comment]
Hi guys. I haven't uploaded the code, that generates the test set yet. Is it what you are trying to do? Because otherwise, just for predictions you don't need the test set - you can just use the demo code as template.

**Comment by YYfangzi** [comment]
@eldar Thank you for very much!
The MPII dataset has about  25k images.I want to know the training code you provided is on these whole 25k images  and how about its test dataset? 
The model is acquired from training on the train dataset and then the model is used on the test dataset to get evaluation results such as mAP. The demo code can provide visual results just on a single image but for evaluation, the model got from trainning may be used on the test set.
We want to train on our own dataset and then evaluation on our test set ,so we just have those problems.Thank you for your attention！

**Comment by Mourula** [comment]
@eldar How should we preprocess the image(s) that we feed into the demo code? I guess you have preprocessed (the scaling and cropping) the training and testing images based on the annotations' spots (head size etc.)?

**Comment by gsoykan** [comment]
@eldar I am also suffering from the same issue. Would you please upload the code that generates the test set? I am trying to replicate your work with Julia Lang by using Knet platform. I would really appreciate if you do upload the code, because I have already developed and trained my neural network. However, I can not test it.

**Comment by Ai-econ** [comment]
@eldar, Thanks for splendid work for pose-estimation. Would you upload the code that generates the test set?
