### ISSUE TITLE
Run single person demo with error ...

### ISSUE THREAD

**Issue by ckl8964** [eldar/pose-tensorflow#21]
Hi,

I just follow the step to have a trial on the "single person" with the following step :
************************************************************************************************
# Download pre-trained model files
$ cd models/mpii
$ ./download_models.sh
$ cd -

# Run demo of single person pose estimation
$ TF_CUDNN_USE_AUTOTUNE=0 python demo/singleperson.py
************************************************************************************************

However, it shows the error from python interpreter :
************************************************************************************************
Traceback (most recent call last):
  File "demo/singleperson.py", line 9, in <module>
    from nnet import predict
ImportError: No module named nnet
************************************************************************************************ 

How can I fix it ?

Thanks.

**Comment by eldar** [comment]
This is strange. Are you using virtualenv? Does `python` that you are calling correspond to python3?

**Comment by bhack** [comment]
In many debian/ubuntu distributions python 3.x is called python3 and pip pip3

**Comment by eldar** [comment]
Yeah, I was relying on virtualenv or anaconda, that make a `python` alias for the python3. Nevertheless I update the instructions to use `python3` explicitly. Please let me know if this was the issue.

**Comment by ckl8964** [comment]
After created another virtualenv with python 3 and installed "python3-tk", it works fine in my case ! Thanks.

**Comment by ckl8964** [comment]
Poor to say that it's ok for singleperson.py demo, but run with exception raised while testing the multiperson.py demo. The below is the log printout to the console :+1: 

*************************************************************************************************************
WARNING:tensorflow:From demo/../nnet/pose_net.py:54: calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training is deprecated and will be removed after 2017-08-01.
Instructions for updating:
Pass is_training directly to the network instead of the arg_scope.
WARNING:tensorflow:From demo/../nnet/pose_net.py:54: calling resnet_arg_scope (from tensorflow.contrib.slim.python.slim.nets.resnet_utils) with is_training is deprecated and will be removed after 2017-08-01.
Instructions for updating:
Pass is_training directly to the network instead of the arg_scope.
2017-07-13 15:56:13.280592: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-13 15:56:18.049322: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.066129: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.090328: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.101826: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.103812: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.105701: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.127367: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.133619: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.136651: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.148389: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.161948: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.177901: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.189893: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.199173: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.201468: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.208072: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.209383: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.217818: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.225652: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.233371: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.237324: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.244317: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.249555: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.259217: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.261564: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.267703: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.273498: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.285512: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.292987: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.301539: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.307908: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.321848: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.329272: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.337706: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.339188: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.346433: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.349356: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.357617: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.365955: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.373681: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.381338: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.385071: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.392983: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.411769: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.423678: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.425587: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.434041: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.444235: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.447394: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.448745: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.453353: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.462559: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.466014: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.474471: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.493216: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.495808: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.497302: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.503992: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.509508: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.525126: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.527446: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.536002: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.541137: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.546997: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.553169: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.561258: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.562769: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.567519: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.576547: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.581362: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.594074: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.596124: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.597462: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.601080: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.607526: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.611523: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.625361: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.627587: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.629294: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.633358: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.650439: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.651817: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.653118: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.654317: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.657467: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.669310: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.670966: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.672369: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.677384: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.684963: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.693130: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.696172: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.701646: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.708800: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.720163: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.737584: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.742926: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.749666: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.764680: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.771759: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.783560: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.799200: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.807278: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.813262: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.825341: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.826745: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.828002: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.837227: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.846528: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.848232: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.849619: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.857157: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.858486: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.873436: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.874785: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.882170: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.884365: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.907881: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.913463: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.915542: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.920503: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.922051: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.923501: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.924834: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.926346: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.927545: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.937390: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.946640: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.951229: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.953172: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.955944: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.959445: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.963187: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.965884: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.967316: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.974813: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.980323: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.981922: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.987101: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.989985: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.995089: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:18.998261: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.002083: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.006402: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.009813: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.014660: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.018685: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.020107: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.022357: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.024815: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.027738: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.030818: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.036036: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.038605: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.041110: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.044383: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.048712: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.051684: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.054729: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.058954: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.062663: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.067267: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.073785: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.081499: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.084485: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.087551: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.090111: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.094791: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.098414: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.101514: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.104007: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.107081: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.109932: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.112737: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.115684: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.121887: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.125185: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.132016: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.136037: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.137650: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
2017-07-13 15:56:19.159470: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: Read less bytes than requested
Traceback (most recent call last):
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
	 [[Node: save/RestoreV2_525 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_525/tensor_names, save/RestoreV2_525/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/demo_multiperson.py", line 33, in <module>
    sess, inputs, outputs = predict.setup_pose_prediction(cfg)
  File "demo/../nnet/predict.py", line 21, in setup_pose_prediction
    restorer.restore(sess, cfg.init_weights)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
	 [[Node: save/RestoreV2_525 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_525/tensor_names, save/RestoreV2_525/shape_and_slices)]]

Caused by op 'save/RestoreV2_525', defined at:
  File "demo/demo_multiperson.py", line 33, in <module>
    sess, inputs, outputs = predict.setup_pose_prediction(cfg)
  File "demo/../nnet/predict.py", line 13, in setup_pose_prediction
    restorer = tf.train.Saver()
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/kl/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): Read less bytes than requested
	 [[Node: save/RestoreV2_525 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_525/tensor_names, save/RestoreV2_525/shape_and_slices)]]
*************************************************************************************************************

Any idea ?

Thanks.

**Comment by eldar** [comment]
Could it be that the model files  are corrupt? Error message `read less bytes than requested` suggests that to me.

```
$ md5sum models/coco/coco-resnet-101.*
6ac5e65465b72cc49ac6328e6b0b573c  models/coco/coco-resnet-101.data-00000-of-00001
6860d6a15735c5b81aabf0d18ec36c20  models/coco/coco-resnet-101.index
a9548d0a6f3ac07e3c7408ea80da317a  models/coco/coco-resnet-101.meta
```

Can you re-download the models and try again?

**Comment by ckl8964** [comment]
Oh ! Yes, thanks, the large data file is corrupted. Now, both demo runs perfectly ! Thanks.

**Comment by 710038817** [comment]
I cannot download the model files for single person demo.  Only the 3rd file is fully downloaded in the following three files:

> curl -L -O https://datasets.d2.mpi-inf.mpg.de/deepercut-models-tensorflow/mpii-single-resnet-101.data-00000-of-00001

> curl -L -O https://datasets.d2.mpi-inf.mpg.de/deepercut-models-tensorflow/mpii-single-resnet-101.meta

> curl -L -O https://datasets.d2.mpi-inf.mpg.de/deepercut-models-tensorflow/mpii-single-resnet-101.index

Can you share these model files or provide any other solutions? Email: 710038817@qq.com
