### ISSUE TITLE
No module named 'nms_grid'

### ISSUE THREAD

**Issue by livingbeams** [eldar/pose-tensorflow#26]
I am trying to run the demo_multiverision.py script in a python 3.5 + win10 setup.
I get the error: No module named 'nms_grid'
I cannot find any information about this module

**Comment by eldar** [comment]
Hey,

For multi-person code there are two modules (nms_grid is one of them) that are written in C++ and are accessed from python via Cython bindings. They are built with `compile.sh` script on Linux, and I haven't actually wrote the script to do it on Windows. I guess I will need to compile the DLLs and distribute them for Windows, but I will only be able to do a week and a half later.

Cheers,
Eldar.

**Comment by Observerspy** [comment]
hi，did you deal with this question？

**Comment by gundamkeroro** [comment]
Hi I have the same problem, I'm in Mac pro.

**Comment by qqsh0214** [comment]
I get the same error:No module named 'nms_grid'. First, I think that it is caused by not installing some python packages called nms_grid. However, I can't google any information about such a package. Later, due to the eldar's comments, I find it is because the command "./compile.sh" doesn't run. Finally, I run the command in compile.sh one by one in hand and solve the problem. I hope that it can help you.

**Comment by AVCarreiro** [comment]
@qqsh0214 I'm in Windows 10 and even running the commands individually does not work. Seems that some c++ interfaces are different than expected.

**Comment by qqsh0214** [comment]
@AVCarreiro Maybe. I was in Linux.

**Comment by stephenbaek** [comment]
Succeeded in compiling on a Windows 10 machine. MS Surface Book, Visual Studio 2015 Community Ed.

Here's what I did:
1. Delete '-Wno-cpp' and '-Wno-unused-function' flags in 'lib/coco/PythonAPI/setup.py' file. Those are just flags to suppress warning messages. Thus, doesn't matter if you remove them.
2. On Command Prompt, run 'cd lib/coo/pythonapi' and then 'python3 setup.py build_ext --inplace'. This way, pycoco tool is compiled successfully.
3. Add '#include <array>' in 'lib/multicut_cython/solve_nl_lmp.hxx'
4. On Command Prompt, run 'cd ../../multicut_cython' and then 'python3 setup.py build_ext --inplace'.
5. Add '#include <array>' in 'lib/nms_cython/include/nms_scoremap.hxx'
6. Finally, run 'cd ../nms_cython' and then 'python3 setup.py build_ext --inplace'.

I've only tested with 'demo/demo_multiperson.py'. Might not work with other functionalities (e.g. re-training, etc.)----haven't tested yet. Maybe @eldar could confirm. Thank you for the awesome code btw. Super cool!

**Comment by AVCarreiro** [comment]
@stephenbaek Thanks for sharing! But do you actually mean to add an empty #include in steps 3/5? What does that mean? I thought it always requires a "file" or <file>. For me it complains that it expected a filename and found a newline. 

And thanks to @eldar for the code! :)

**Comment by stephenbaek** [comment]
@AVCarreiro Sorry. Yes I meant to type '\<array>' but I forgot Markdown considers what's in the angle brackets as some kind of a command... :) Glad you figured out (and it worked)!! I've also edited my original comment.

**Comment by bhalajin** [comment]
@eldar , do you have the distribution for Windows?

**Comment by am-khan** [comment]
Having included @stephenbaek fix: I now get this (on macOS)

whilst running the multicut_cython/setup.py:

running build_ext
building 'multicut' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I/usr/local/lib/python3.6/site-packages/numpy/core/include -I. -Iinclude -Isrc -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c multicut.cpp -o build/temp.macosx-10.13-x86_64-3.6/multicut.o -std=c++11 -O3 -DHAVE_CPP11_INITIALIZER_LISTS
In file included from multicut.cpp:573:
In file included from /usr/local/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /usr/local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /usr/local/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1809:
/usr/local/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
In file included from multicut.cpp:580:
./solve_nl_lmp.hxx:1:9: warning: 'HAVE_CPP11_INITIALIZER_LISTS' macro redefined [-Wmacro-redefined]
#define HAVE_CPP11_INITIALIZER_LISTS
        ^
<command line>:2:9: note: previous definition is here
#define HAVE_CPP11_INITIALIZER_LISTS 1
        ^
multicut.cpp:1970:3: error: no matching function for call to 'solve_nl_lmp_cpp'
  solve_nl_lmp_cpp((&(*__Pyx_BufPtrCContig2d(__pyx_t_5numpy_float64_t *, __pyx_pybuffernd_unary_array.rcbuffer->pybuffer.buf, __pyx_t_7, __pyx_pybuffernd_unary_array.diminfo[0].strides, __pyx_t_8, __pyx_pybuffernd_unary_array.dim...
  ^~~~~~~~~~~~~~~~
./solve_nl_lmp.hxx:27:6: note: candidate function not viable: no known conversion from '__pyx_t_5numpy_uint64_t *' (aka 'unsigned long *') to 'uint64_t *' (aka 'unsigned long long *') for 14th argument
void solve_nl_lmp_cpp(double *unValues, int un_H, int un_W,
     ^
2 warnings and 1 error generated.

**Comment by am-khan** [comment]
To my understanding the problem is that clang doesn't finish making the multicut module anymore - I don't know C++ so i don't know why the conversion doesn't work.
My GCC version is 9.00 and 64bit. So long is just 64bit and long long is 128bit?
Either way the conversion is to a larger size so whats the problem?

**Comment by 3073** [comment]
@eldar: Have you finished working on nms_grid for windows?

**Comment by beyzozhan** [comment]
I followed @stephenbaek  instructions but still the nms_grid file is not recognized by pycharm. Maybe pycharm cannot import "nms_grid.pyd" file or  stephenbaek's instructions is not the exact solution for me.  Although it is not recognized, code can run. But now i get this error;

Traceback (most recent call last):
  File "C:/Users/user/Desktop/bitirme-2/pose-tensorflow-master/demo/demo_multiperson.py", line 46, in <module>
    unLab, pos_array, unary_array, pwidx_array, pw_array = eval_graph(sm, detections)
  File "C:\Users\user\Desktop\bitirme-2\pose-tensorflow-master\multiperson\predict.py", line 75, in eval_graph
    cur_prob, ptidx = sm.eval(cidx1, cidx2, detections)
  File "C:\Users\user\Desktop\bitirme-2\pose-tensorflow-master\multiperson\predict.py", line 324, in eval
    cur_prob = self.compute_different_part_pairwise(cidx1, cidx2, detections, ptidx, num_edges)
  File "C:\Users\user\Desktop\bitirme-2\pose-tensorflow-master\multiperson\predict.py", line 364, in compute_different_part_pairwise
    featAugm[:, :-1] = (featAugm[:, :-1] - self.X_min[cidx1][cidx2]) / (self.X_max[cidx1][cidx2] - self.X_min[cidx1][cidx2])
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'


How can i fix this error?

**Comment by junedgar** [comment]
Solving the '__pyx_t_5numpy_uint64_t *' (aka 'unsigned long *') to 'uint64_t *'  problem, following:
1、change the  __pyx_t_5numpy_uint64_t to  __pyx_t_5numpy_uint32_t in line 2022 of multicut.cpp.
2、change the  uint64_t to uint32_t in line 30 and 67 in solve_nl_lmp.hxx.
Then you can run the compile.sh success. But I don't konw what the effect for the project.

**Comment by eliaed** [comment]
I followed @stephenbaek instructions but still in  point 2 ('python3 setup.py build_ext --inplace')
i get an error :
running build_ext
building 'pycocotools._mask' extension
error: Unable to find vcvarsall.bat
i downloaded visual studio but it didnt fixed it .
can someone help me?

**Comment by sachinanand** [comment]
@eliaed  were you able to resolve the error above? I am having the same error on my Windows 10 machine.
