### ISSUE TITLE
How to save test result and evaluate on LSP dataset?

### ISSUE THREAD

**Issue by zilesazoyi2** [eldar/pose-tensorflow#43]
Thanks for you code !＼（＾ｏ＾）／～really help me  a lot 

I want to save the test result use test.py  and i cant find predictions.mat.Could you give me some advice?

  scipy.io.savemat('predictions.mat', mdict={'joints': predictions})

sun@sunwin:~/0newcodedown/pose-tensorflow-mastermy$ python eval_pck.py
Traceback (most recent call last):
  File "eval_pck.py", line 8, in <module>
    from dataset.factory import create as dataset_create
ImportError: No module named dataset.factory
sun@sunwin:~/0newcodedown/pose-tensorflow-mastermy$ python test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    from dataset.factory import create as create_dataset
ImportError: No module named dataset.factory

**Comment by monajalal** [comment]
@zilesazoyi2  can you please guide how to test on LSP dataset? Can you show the steps?

**Comment by ZP-Guo** [comment]
Great,I have the same idea with you.Now I am fallowing your work.Can you share your method.Thank you so much.

**Comment by ZP-Guo** [comment]
> Great,I have the same idea with you.Now I am fallowing your work.Can you share your method.Thank you so much.

Oh, I do it. Just to  modify mpii files and the train.py can run.
