### ISSUE TITLE
Issue with demo - ValueError: scale cannot be an integer: False

### ISSUE THREAD

**Issue by archenroot** [eldar/pose-tensorflow#54]
I am using latest dev branch of tensorflow and getting into this issue.

```
zangetsu@nunik ~/proj/pose-tensorflow $ TF_CUDNN_USE_AUTOTUNE=0 python3 demo/singleperson.py
Traceback (most recent call last):
  File "demo/singleperson.py", line 17, in <module>
    sess, inputs, outputs = predict.setup_pose_prediction(cfg)
  File "demo/../nnet/predict.py", line 11, in setup_pose_prediction
    outputs = pose_net(cfg).test(inputs)
  File "demo/../nnet/pose_net.py", line 90, in test
    heads = self.get_net(inputs)
  File "demo/../nnet/pose_net.py", line 86, in get_net
    net, end_points = self.extract_features(inputs)
  File "demo/../nnet/pose_net.py", line 54, in extract_features
    with slim.arg_scope(resnet_v1.resnet_arg_scope(False)):
  File "/usr/lib64/python3.4/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 257, in resnet_arg_scope
    weights_regularizer=regularizers.l2_regularizer(weight_decay),
  File "/usr/lib64/python3.4/site-packages/tensorflow/contrib/layers/python/layers/regularizers.py", line 92, in l2_regularizer
    raise ValueError('scale cannot be an integer: %s' % (scale,))
ValueError: scale cannot be an integer: False

```
As this is new for me I have not much idea how to resolve...

**Comment by cellistigs** [comment]
I am also running into this same issue, are there any updates?

**Comment by ayanasser** [comment]
i have the same problem

**Comment by eldar** [comment]
Hi, I just checked with the latest version of the code (python 3.6, TF 1.12) and it worked. If you don't use Python 3.6, can you please try that first (you can use conda if the version of python in your OS is different).

**Comment by ayanasser** [comment]
@eldar i am using the latest version but the error is still exist , do you run this code inside docker container or just on your machine ?

**Comment by eldar** [comment]
I'm not using Docker, I run it directly on Debian 9. Which version of python exactly are you using? And of Tensorflow?

**Comment by ayanasser** [comment]
i am using ubuntu 16.04
and Python 3.6.7 |Anaconda custom (64-bit)| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
and tensorflow 1.12.0

**Comment by eldar** [comment]
Also, can you please post the exact error message. The error message in the first pose contains contains this stack trace

```
zangetsu@nunik ~/proj/pose-tensorflow $ TF_CUDNN_USE_AUTOTUNE=0 python3 demo/singleperson.py
Traceback (most recent call last):
  File "demo/../nnet/pose_net.py", line 54, in extract_features
    with slim.arg_scope(resnet_v1.resnet_arg_scope(False)):
```

But the call on line 54 in the file `nnet/pose_net.py` calls `resnet_v1.resnet_arg_scope()` without `False` argument, so you must have a different error message.

**Comment by ayanasser** [comment]
Traceback (most recent call last):
  File "video_pose.py", line 50, in <module>
    sess, inputs, outputs = predict.setup_pose_prediction(cfg)
  File "/media/biohelwan/New Volume/Got/exercise-pose-analyzer/nnet/predict.py", line 11, in setup_pose_prediction
    outputs = pose_net(cfg).test(inputs)
  File "/media/biohelwan/New Volume/Got/exercise-pose-analyzer/nnet/pose_net.py", line 90, in test
    heads = self.get_net(inputs)
  File "/media/biohelwan/New Volume/Got/exercise-pose-analyzer/nnet/pose_net.py", line 86, in get_net
    net, end_points = self.extract_features(inputs)
  File "/media/biohelwan/New Volume/Got/exercise-pose-analyzer/nnet/pose_net.py", line 54, in extract_features
    with slim.arg_scope(resnet_v1.resnet_arg_scope(False)):
  File "/home/biohelwan/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 257, in resnet_arg_scope
    weights_regularizer=regularizers.l2_regularizer(weight_decay),
  File "/home/biohelwan/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/regularizers.py", line 92, in l2_regularizer
    raise ValueError('scale cannot be an integer: %s' % (scale,))
ValueError: scale cannot be an integer: False

![error](https://user-images.githubusercontent.com/26551277/54495119-b606f580-48e9-11e9-88ba-c9d42134879e.png)

**Comment by eldar** [comment]
Can you check the line 54 in the module `nnet/pose_net.py`? According to your stack trace it is 

```
with slim.arg_scope(resnet_v1.resnet_arg_scope(False)):
```

but in the repository https://github.com/eldar/pose-tensorflow/blob/master/nnet/pose_net.py#L54
 it is:
```
with slim.arg_scope(resnet_v1.resnet_arg_scope()):
```

Otherwise, can try and change this line to:

```
with slim.arg_scope(resnet_v1.resnet_arg_scope(weight_decay=self.cfg.weight_decay)):
```

**Comment by ayanasser** [comment]
for make everything is clear , i am clone this repo https://github.com/PJunhyuk/exercise-pose-analyzer
and this error happen when i am run this line 
python video_pose.py -f '{video_file_name}'

**Comment by eldar** [comment]
OK, then that version of the code contains a bug that I just mentioned: `resnet_v1.resnet_arg_scope(False)` and it should be just `resnet_v1.resnet_arg_scope(False)`. Please report this bug to the that repository, because the version in this repository is already fixed. I'm therefore closing this issue.

**Comment by ayanasser** [comment]
thank you sooo much
