### ISSUE TITLE
I got a “out of range error”,please help me

### ISSUE THREAD

**Issue by luoyangtractor** [eldar/pose-tensorflow#62]
I got this problem

2018-01-25 17:50:33.199858: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-01-25 17:50:33.200658: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
2018-01-25 17:50:33.210929: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: Read less bytes than requested
Traceback (most recent call last):
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
	 [[Node: save/RestoreV2_523 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_523/tensor_names, save/RestoreV2_523/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/singleperson.py", line 17, in <module>
    sess, inputs, outputs = predict.setup_pose_prediction(cfg)
  File "/home/wzh/pose-tensorflow/nnet/predict.py", line 24, in setup_pose_prediction
    restorer.restore(sess, cfg.init_weights)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
	 [[Node: save/RestoreV2_523 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_523/tensor_names, save/RestoreV2_523/shape_and_slices)]]

Caused by op 'save/RestoreV2_523', defined at:
  File "demo/singleperson.py", line 17, in <module>
    sess, inputs, outputs = predict.setup_pose_prediction(cfg)
  File "/home/wzh/pose-tensorflow/nnet/predict.py", line 14, in setup_pose_prediction
    restorer = tf.train.Saver()
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/wzh/anaconda2/envs/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): Read less bytes than requested
	 [[Node: save/RestoreV2_523 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_523/tensor_names, save/RestoreV2_523/shape_and_slices)]]

 I dont know  is there something wrong with downloaded model? 
@eldar 
@andreas-eberle

**Comment by tongpinmo** [comment]
@luoyangtractor have you ever solved the problem?i have the same issue

**Comment by peach1995** [comment]
I have the same issue too.Have you solved the problem?

**Comment by KaaiLee** [comment]
I have the same issue too.but i have fix it.This problem is because the model in the previous step is not completely downloaded.

**Comment by eldar** [comment]
This indeed looks like the downloaded file is corrupt, therefore I close the issue.

**Comment by swg209** [comment]
@eldar  could you please share the file?  I downloaded the file in download_models.sh in coco ,but still get this problem. Thx

**Comment by swg209** [comment]
@KaaiLee  Hello, could you tell me how to fix the problem in detail? redownload which file?  Thx.

**Comment by KaaiLee** [comment]
> @KaaiLee Hello, could you tell me how to fix the problem in detail? redownload which file? Thx.
You can try to downloads for the link  https://pan.baidu.com/s/1_9RigaJDNJfGg0Xd6pERiA 提取码: q553

**Comment by KaaiLee** [comment]
> @KaaiLee Hello, could you tell me how to fix the problem in detail? redownload which file? Thx.
You can try to downloads for the link https://pan.baidu.com/s/1_9RigaJDNJfGg0Xd6pERiA 提取码: q553
